# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options

# you can delete this line if you're not using Docker
#image: busybox:latest

before_script:
  - echo "Before script section"
  - echo "For example you might run an update here or install a build dependency"
  - echo "Or perhaps you might print out some debugging details"

after_script:
  - echo "After script section"
  - echo "For example you might do some cleanup here"

build1:
  stage: build
  script:
    - go build -o oke-admission-webhook
    - docker build --no-cache -t iad.ocir.io/espsnonprodint/autostg/oke-admission-webhook:v1 .
    - rm -rf oke-admission-webhook
    - docker push iad.ocir.io/espsnonprodint/autostg/oke-admission-webhook:v1
    - kubectl replace --force -f deployment/validatingwebhook.yaml
    - kubectl replace --force -f deployment/deployment.yaml
    - kubectl replace --force -f deployment/service.yaml

test1:
  stage: test
  script:
    - kubectl replace --force -f deployment/test-service1.yaml
