apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kube-system
  name: oke-admission-webhook-deployment
  labels:
    app: oke-admission-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oke-admission-webhook
  template:
    metadata:
      labels:
        app: oke-admission-webhook
    spec:
      containers:
        - name: oke-admission-webhook
          image: iad.ocir.io/espsnonprodint/autostg/oke-admission-webhook:v1
          imagePullPolicy: Always
          args:
            - -alsologtostderr
            - -v=4
            - 2>&1
