apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  name: oke-admission-webhook-svc
  labels:
    app: oke-admission-webhook
spec:
  ports:
  - port: 443
    targetPort: 443
  selector:
    app: oke-admission-webhook
