apiVersion: v1
kind: Service
metadata:
  labels:
    name: test-service
  name: test-service-nodeport
  namespace: default
spec:
  ports:
    - port: 7766
      targetPort: 8888
      nodePort: 30301
  type: NodePort
